Exceptions raised by os.utime builtin function now include the related
filename
