Return ``NULL`` for ``PyTrace_RETURN`` events caused by an exception
